# permissions for end users to view quotas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: quota-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: quota
    app.kubernetes.io/part-of: quota
    app.kubernetes.io/managed-by: kustomize
  name: quota-viewer-role
rules:
- apiGroups:
  - serverless.pml.com.cn
  resources:
  - quotas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - serverless.pml.com.cn
  resources:
  - quotas/status
  verbs:
  - get
