---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - serverless.pml.com.cn
  resources:
  - quotas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - serverless.pml.com.cn
  resources:
  - quotas/finalizers
  verbs:
  - update
- apiGroups:
  - serverless.pml.com.cn
  resources:
  - quotas/status
  verbs:
  - get
  - patch
  - update
